/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PhoneRental;

import MySQLConnection.MySQLConnection;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Customers.CustomerLanding;
import HomeLanding.HomeLanding;
import javax.swing.JFrame;

/**
 *
 * @author rahulb
 */
public class CustomerPhoneComplain extends javax.swing.JFrame {

    /**
     * Creates new form CustomerLaptopReturn
     */
     MySQLConnection c = new MySQLConnection();
    public CustomerPhoneComplain() {
        initComponents();
        DisplayPhoneOnRent();
        txtProductID.setEditable(false);
        txtCustomerId.setEditable(false);
        txtRentId.setEditable(false);
//        DisplaylaptopOnRent2();
             this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }
public CustomerPhoneComplain(String s) {
        initComponents();
        showData(s);
        DisplayPhoneOnRent();
        txtProductID.setEditable(false);
        txtCustomerId.setEditable(false);
        txtRentId.setEditable(false);
             this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtCustomerId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtProductID = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtRentId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblPhoneOnRent = new javax.swing.JTable();
        btnRaiseComplaint = new javax.swing.JButton();
        btnPayment = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1300, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(txtCustomerId, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 360, 299, 30));

        jLabel1.setFont(new java.awt.Font("Oriya MN", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Customer ID :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 360, 119, 30));

        txtProductID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProductIDActionPerformed(evt);
            }
        });
        jPanel1.add(txtProductID, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 410, 299, 32));

        jLabel7.setFont(new java.awt.Font("Oriya MN", 3, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Product ID :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 410, 119, 30));
        jPanel1.add(txtRentId, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 460, 299, 29));

        jLabel2.setFont(new java.awt.Font("Oriya MN", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Rent ID :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 460, 88, 29));

        tblPhoneOnRent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Rent ID"
            }
        ));
        tblPhoneOnRent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPhoneOnRentMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblPhoneOnRent);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, 580, 220));

        btnRaiseComplaint.setBackground(new java.awt.Color(51, 51, 51));
        btnRaiseComplaint.setFont(new java.awt.Font("Oriya MN", 3, 18)); // NOI18N
        btnRaiseComplaint.setForeground(new java.awt.Color(255, 255, 255));
        btnRaiseComplaint.setText("Raise a Complain");
        btnRaiseComplaint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRaiseComplaintMouseClicked(evt);
            }
        });
        btnRaiseComplaint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRaiseComplaintActionPerformed(evt);
            }
        });
        jPanel1.add(btnRaiseComplaint, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, -1, 40));

        btnPayment.setBackground(new java.awt.Color(51, 51, 51));
        btnPayment.setFont(new java.awt.Font("Oriya MN", 3, 18)); // NOI18N
        btnPayment.setForeground(new java.awt.Color(255, 255, 255));
        btnPayment.setText("Payment");
        btnPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaymentActionPerformed(evt);
            }
        });
        jPanel1.add(btnPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, 135, 40));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PhoneRental/PhoneRental/payment.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 390, 310));

        jLabel8.setFont(new java.awt.Font("Oriya MN", 3, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Manage Phone Rent");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, 288, 67));

        btnLogout.setBackground(new java.awt.Color(51, 51, 51));
        btnLogout.setFont(new java.awt.Font("Oriya MN", 3, 14)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("Log Out");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 450, -1, 35));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 2110, 1340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblPhoneOnRentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPhoneOnRentMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblPhoneOnRent.getModel();
        int MyIndex = tblPhoneOnRent.getSelectedRow();
        txtRentId.setText(model.getValueAt(MyIndex,1).toString());
        txtProductID.setText(model.getValueAt(MyIndex,0).toString());
    }//GEN-LAST:event_tblPhoneOnRentMouseClicked

    private void txtProductIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProductIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProductIDActionPerformed

    private void btnPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaymentActionPerformed
        // TODO add your handling code here:
        String sql1 ="UPDATE Customer SET phone_payment_status = 'Done', PhoneApprove = NULL ,PhoneDelay = NULL,PhoneFine = NULL,PhonePrice = NULL,"
                + "PhoneComplain = NULL,PhoneRentID = NULL,PhoneRentDate = NULL,PhoneReturnDate = NULL, PhoneID = NULL WHERE CustomerID = '"+txtCustomerId.getText()+"' ";
            c.updateDatabase(sql1);
            JOptionPane.showMessageDialog(this,"Payment Done");
    }//GEN-LAST:event_btnPaymentActionPerformed

    private void btnRaiseComplaintMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRaiseComplaintMouseClicked
        // TODO add your handling code here:
        try {
        String sql="UPDATE Customer SET PhoneComplain = 'Requested'  WHERE CustomerID = '"+txtCustomerId.getText()+"' ";
        c.updateDatabase(sql);
        JOptionPane.showMessageDialog(this," Successfully Raised Request");
        String sql1 = "UPDATE Phone SET Service = 'Requested'  WHERE Productid = '"+txtProductID.getText()+"' ";
        c.updateDatabase(sql1);
         
            }
      catch (Exception ex) {
      System.out.println(ex);}
    }//GEN-LAST:event_btnRaiseComplaintMouseClicked

    private void btnRaiseComplaintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRaiseComplaintActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnRaiseComplaintActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        HomeLanding lr = new HomeLanding();
        lr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerPhoneComplain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerPhoneComplain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerPhoneComplain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerPhoneComplain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerPhoneComplain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnPayment;
    private javax.swing.JButton btnRaiseComplaint;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblPhoneOnRent;
    private javax.swing.JTextField txtCustomerId;
    private javax.swing.JTextField txtProductID;
    private javax.swing.JTextField txtRentId;
    // End of variables declaration//GEN-END:variables

            
    private void DisplayPhoneOnRent() {
        
         String reg,brand,carmodel,status,price;
        try{


            String sql = "select * from Customer where CustomerID = '"+txtCustomerId.getText()+"' and PhoneApprove = 'Booked' ";
            ResultSet rs = c.selectDatabase(sql);
            
            
            DefaultTableModel model =(DefaultTableModel) tblPhoneOnRent.getModel();
            int rowCount = model.getRowCount();
            for (int i = rowCount - 1; i >= 0; i--) 
            {
            model.removeRow(i);
            }


            while (rs.next()) {
                  reg = rs.getString(38);
                 brand = rs.getString(41);
//               
                  String[] row = {reg,brand};
                  model.addRow(row);
                               
            }
        
        } catch (SQLException e)
        {
            e.printStackTrace();
            
            
        }
    }

    private void showData(String s) {
         txtCustomerId.setText(s);
    }

}
