/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Admin;

import HomeLanding.HomeLanding;
import com.formdev.flatlaf.FlatDarkLaf;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.UIManager;

/**
 *
 * @author monicasriramreddy
 */
public class AdminLandingJFrame extends javax.swing.JFrame {

    /**
     * Creates new form Splash
     */
    public AdminLandingJFrame() {
        initComponents();
     this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane2 = new javax.swing.JSplitPane();
        jPanel3 = new javax.swing.JPanel();
        btnVehicleAdmin3 = new javax.swing.JButton();
        btnGadgetAdmin3 = new javax.swing.JButton();
        btnVehicleServicesAdmin3 = new javax.swing.JButton();
        btnGadgetServicesAdmin3 = new javax.swing.JButton();
        Logout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnGadgetServicesAdmin4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane2.setBackground(new java.awt.Color(51, 51, 0));

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));

        btnVehicleAdmin3.setBackground(new java.awt.Color(51, 51, 51));
        btnVehicleAdmin3.setFont(new java.awt.Font("Oriya MN", 3, 13)); // NOI18N
        btnVehicleAdmin3.setForeground(new java.awt.Color(255, 255, 255));
        btnVehicleAdmin3.setText("Vehicle Admin");
        btnVehicleAdmin3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVehicleAdminActionPerformed(evt);
            }
        });

        btnGadgetAdmin3.setBackground(new java.awt.Color(51, 51, 51));
        btnGadgetAdmin3.setFont(new java.awt.Font("Oriya MN", 3, 13)); // NOI18N
        btnGadgetAdmin3.setForeground(new java.awt.Color(255, 255, 255));
        btnGadgetAdmin3.setText("Gadget Admin");
        btnGadgetAdmin3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGadgetAdminActionPerformed(evt);
            }
        });

        btnVehicleServicesAdmin3.setBackground(new java.awt.Color(51, 51, 51));
        btnVehicleServicesAdmin3.setFont(new java.awt.Font("Oriya MN", 3, 13)); // NOI18N
        btnVehicleServicesAdmin3.setForeground(new java.awt.Color(255, 255, 255));
        btnVehicleServicesAdmin3.setText("Vehicle Services Admin");
        btnVehicleServicesAdmin3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVehicleServicesAdminActionPerformed(evt);
            }
        });

        btnGadgetServicesAdmin3.setBackground(new java.awt.Color(51, 51, 51));
        btnGadgetServicesAdmin3.setFont(new java.awt.Font("Oriya MN", 3, 13)); // NOI18N
        btnGadgetServicesAdmin3.setForeground(new java.awt.Color(255, 255, 255));
        btnGadgetServicesAdmin3.setText("Gadget Services Admin");
        btnGadgetServicesAdmin3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGadgetServicesAdminActionPerformed(evt);
            }
        });

        Logout.setBackground(new java.awt.Color(51, 51, 51));
        Logout.setFont(new java.awt.Font("Oriya MN", 3, 13)); // NOI18N
        Logout.setForeground(new java.awt.Color(255, 255, 255));
        Logout.setText("Logout");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutbtnGadgetAdminActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/administrator.png"))); // NOI18N

        btnGadgetServicesAdmin4.setBackground(new java.awt.Color(51, 51, 51));
        btnGadgetServicesAdmin4.setFont(new java.awt.Font("Oriya MN", 3, 13)); // NOI18N
        btnGadgetServicesAdmin4.setForeground(new java.awt.Color(255, 255, 255));
        btnGadgetServicesAdmin4.setText("Report");
        btnGadgetServicesAdmin4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGadgetServicesAdmin4btnGadgetServicesAdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(btnVehicleAdmin3, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(btnGadgetAdmin3, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(btnVehicleServicesAdmin3)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(btnGadgetServicesAdmin3, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnGadgetServicesAdmin4, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(btnVehicleAdmin3)
                .addGap(17, 17, 17)
                .addComponent(btnGadgetAdmin3)
                .addGap(17, 17, 17)
                .addComponent(btnVehicleServicesAdmin3)
                .addGap(17, 17, 17)
                .addComponent(btnGadgetServicesAdmin3)
                .addGap(18, 18, 18)
                .addComponent(btnGadgetServicesAdmin4)
                .addGap(30, 30, 30)
                .addComponent(Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jSplitPane2.setLeftComponent(jPanel3);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 702, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 622, Short.MAX_VALUE)
        );

        jSplitPane2.setRightComponent(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGadgetServicesAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGadgetServicesAdminActionPerformed
        GadgetServicesAdminPanel view = new GadgetServicesAdminPanel();
        jSplitPane2.setRightComponent(view);// TODO add your handling code here:
    }//GEN-LAST:event_btnGadgetServicesAdminActionPerformed

    private void btnVehicleServicesAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVehicleServicesAdminActionPerformed
        VehicleServicesAdminPanel view = new VehicleServicesAdminPanel();
        jSplitPane2.setRightComponent(view);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVehicleServicesAdminActionPerformed

    private void btnGadgetAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGadgetAdminActionPerformed
        GadgetAdminPanel view = new GadgetAdminPanel();
        jSplitPane2.setRightComponent(view);// TODO add your handling code here:
    }//GEN-LAST:event_btnGadgetAdminActionPerformed

    private void btnVehicleAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVehicleAdminActionPerformed
        VehicleAdminPanel view = new VehicleAdminPanel();
        jSplitPane2.setRightComponent(view);        // TODO add your handling code here:
    }//GEN-LAST:event_btnVehicleAdminActionPerformed

    private void LogoutbtnGadgetAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutbtnGadgetAdminActionPerformed
        // TODO add your handling code here:
        HomeLanding hm = new HomeLanding();
        hm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LogoutbtnGadgetAdminActionPerformed

    private void btnGadgetServicesAdmin4btnGadgetServicesAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGadgetServicesAdmin4btnGadgetServicesAdminActionPerformed
        // TODO add your handling code here:
        BookingStatGraph graph = null;
        try {
            graph = new BookingStatGraph();
        } catch (SQLException ex) {
            Logger.getLogger(AdminLandingJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        jSplitPane2.setRightComponent(graph);
    }//GEN-LAST:event_btnGadgetServicesAdmin4btnGadgetServicesAdminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminLandingJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminLandingJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminLandingJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminLandingJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
try{
        UIManager.setLookAndFeel(new FlatDarkLaf());
        }catch(Exception e){
            e.printStackTrace();
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminLandingJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Logout;
    private javax.swing.JButton btnGadgetAdmin3;
    private javax.swing.JButton btnGadgetServicesAdmin3;
    private javax.swing.JButton btnGadgetServicesAdmin4;
    private javax.swing.JButton btnVehicleAdmin3;
    private javax.swing.JButton btnVehicleServicesAdmin3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSplitPane jSplitPane2;
    // End of variables declaration//GEN-END:variables
}
