/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package LaptopRental;

import HomeLanding.GadgetAdminLandingPage;
import Rental.Notification.Email;
import MySQLConnection.MySQLConnection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import HomeLanding.HomeLanding;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JDialog;
import javax.swing.JFrame;

/**
 *
 * @author rahulb
 */
public class LaptopRentJFrame extends javax.swing.JFrame {

    /**
     * Creates new form RentJFrame
     */
    MySQLConnection c = new MySQLConnection();
    Email e = new Email();
    public LaptopRentJFrame() {
        initComponents();

        DisplayLaptopOnRent();
        DisplayLaptopRentalRequest();
        txtCustomerId.setEditable(false);
        txtProductId.setEditable(false);
        txtRentDate.setEditable(false);
        txtReturnDate.setEditable(false);
        txtEmail.setEditable(false);
             this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblLaptopOnRent = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblLaptopRentalRequest = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblCustomerId = new javax.swing.JLabel();
        txtCustomerId = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtProductId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtRentID = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtRentDate = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtReturnDate = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        btnAproove = new javax.swing.JButton();
        btnDeny = new javax.swing.JButton();
        btnManagelaptop = new javax.swing.JButton();
        btnReturnLaptop = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1300, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Oriya MN", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Rent Laptop");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, 34));

        jLabel2.setFont(new java.awt.Font("Oriya MN", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Laptops on Rent");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        tblLaptopOnRent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Rent ID", "Customer ID", "Rent Fee"
            }
        ));
        tblLaptopOnRent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLaptopOnRentMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblLaptopOnRent);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 484, 131));

        jLabel11.setFont(new java.awt.Font("Oriya MN", 3, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Rental Request");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        tblLaptopRentalRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer ID", "Product ID", "Rent Date", "Return Date", "Fee"
            }
        ));
        tblLaptopRentalRequest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLaptopRentalRequestMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblLaptopRentalRequest);
        if (tblLaptopRentalRequest.getColumnModel().getColumnCount() > 0) {
            tblLaptopRentalRequest.getColumnModel().getColumn(1).setResizable(false);
        }

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 484, 128));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LaptopRental/LaptopRental/laptop_RentPage.png"))); // NOI18N
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 120, 370, 230));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCustomerId.setFont(new java.awt.Font("Oriya MN", 3, 14)); // NOI18N
        lblCustomerId.setForeground(new java.awt.Color(255, 255, 255));
        lblCustomerId.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCustomerId.setText("Customer ID :");
        jPanel2.add(lblCustomerId, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 116, 40));
        jPanel2.add(txtCustomerId, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 180, 30));

        jLabel5.setFont(new java.awt.Font("Oriya MN", 3, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Product ID :");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 110, 33));
        jPanel2.add(txtProductId, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 180, 30));

        jLabel3.setFont(new java.awt.Font("Oriya MN", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Rent ID :");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 94, -1));
        jPanel2.add(txtRentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 180, 30));

        jLabel6.setFont(new java.awt.Font("Oriya MN", 3, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Rent Date :");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 94, -1));
        jPanel2.add(txtRentDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 160, 30));

        jLabel7.setFont(new java.awt.Font("Oriya MN", 3, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Return Date :");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 110, 42));
        jPanel2.add(txtReturnDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, 160, 30));

        jLabel4.setFont(new java.awt.Font("Oriya MN", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Fee :");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 65, 40));
        jPanel2.add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, 160, 30));

        jLabel8.setFont(new java.awt.Font("Oriya MN", 3, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Email :");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 80, 41));
        jPanel2.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 180, 30));

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 680, 260));

        btnAproove.setBackground(new java.awt.Color(51, 51, 51));
        btnAproove.setFont(new java.awt.Font("Oriya MN", 3, 14)); // NOI18N
        btnAproove.setForeground(new java.awt.Color(255, 255, 255));
        btnAproove.setText("Approve");
        btnAproove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAprooveActionPerformed(evt);
            }
        });
        jPanel3.add(btnAproove, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 350, 120, 41));

        btnDeny.setBackground(new java.awt.Color(51, 51, 51));
        btnDeny.setFont(new java.awt.Font("Oriya MN", 3, 14)); // NOI18N
        btnDeny.setForeground(new java.awt.Color(255, 255, 255));
        btnDeny.setText("Deny");
        btnDeny.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDenyActionPerformed(evt);
            }
        });
        jPanel3.add(btnDeny, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 440, 120, 36));

        btnManagelaptop.setBackground(new java.awt.Color(51, 51, 51));
        btnManagelaptop.setFont(new java.awt.Font("Oriya MN", 3, 14)); // NOI18N
        btnManagelaptop.setForeground(new java.awt.Color(255, 255, 255));
        btnManagelaptop.setText("Manage Laptop");
        btnManagelaptop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagelaptopActionPerformed(evt);
            }
        });
        jPanel3.add(btnManagelaptop, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 440, 140, 36));

        btnReturnLaptop.setBackground(new java.awt.Color(51, 51, 51));
        btnReturnLaptop.setFont(new java.awt.Font("Oriya MN", 3, 14)); // NOI18N
        btnReturnLaptop.setForeground(new java.awt.Color(255, 255, 255));
        btnReturnLaptop.setText("Return Laptop");
        btnReturnLaptop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnLaptopActionPerformed(evt);
            }
        });
        jPanel3.add(btnReturnLaptop, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 440, 160, 35));

        btnLogout.setBackground(new java.awt.Color(51, 51, 51));
        btnLogout.setFont(new java.awt.Font("Oriya MN", 3, 14)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("Back");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jPanel3.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 530, 80, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1750, 1130));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblLaptopRentalRequestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLaptopRentalRequestMouseClicked
//        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblLaptopRentalRequest.getModel();
        int MyIndex = tblLaptopRentalRequest.getSelectedRow();
        txtCustomerId.setText(model.getValueAt(MyIndex,0).toString());
        txtRentDate.setText(model.getValueAt(MyIndex,2).toString());
        txtReturnDate.setText(model.getValueAt(MyIndex,3).toString());
        txtProductId.setText((model.getValueAt(MyIndex, 1).toString()));
        txtPrice.setText((model.getValueAt(MyIndex, 4).toString()));
        
        
    }//GEN-LAST:event_tblLaptopRentalRequestMouseClicked

    private void btnAprooveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAprooveActionPerformed
        // TODO add your handling code here:
        
       try{
            int flag = 0;
                
                //*************************************** Validation of Empty Name Field ***************************************//
                 if(txtRentID.getText().isEmpty()){
                    JOptionPane optionPane = new JOptionPane("Rent ID cannot be empty", JOptionPane.ERROR_MESSAGE);
                    JDialog dialog = optionPane.createDialog("Error Message");
                    dialog.setAlwaysOnTop(true);
                    dialog.setVisible(true);
                    flag = 1;
                }
                String cellPhoneNumber3 = txtRentID.getText();
                Pattern pattern3 = Pattern.compile("^[0-9]{3}$");
                Matcher matcher3 = pattern3.matcher(cellPhoneNumber3);
                if(!matcher3.matches())
                {
                    JOptionPane.showMessageDialog(this,"Enter a Valid Rent ID!");
                    flag = 1;
                    txtRentID.setText("");
                    
                    
                }
                 
             if(flag == 0)
             {   
            String sql="UPDATE Laptop SET CustomerID = '"+txtCustomerId.getText()+"', rentid = '"+txtRentID.getText()+"',Status = 'Booked',rentdate = '"+txtRentDate.getText()+"' ,returndate = '"+txtReturnDate.getText()+"',Price = '"+txtPrice.getText()+"' WHERE Productid = '"+txtProductId.getText()+"' ";
            c.updateDatabase(sql);
            
//************************************************************************************************************   
            String sql1 ="UPDATE Customer SET LaptopApprove = 'Booked', LaptopRentID = '"+ txtRentID.getText()+"'  WHERE CustomerID = '"+txtCustomerId.getText()+"' ";
            c.updateDatabase(sql1);          
//************************************************************************************************************
            String sql2 = "SELECT Email From Customer WHERE CustomerID = '"+txtCustomerId.getText()+"'";
            JOptionPane.showMessageDialog(this,"Request Aprooved");
            ResultSet rs = c.selectDatabase(sql2);
            if(rs.next()){
            String email;
            
            email = rs.getString(1);
//            System.out.println(rs.getString(email));
            txtEmail.setText(email);
            }
//                       String s =c.selectDatabase(sql2).getString(1);
                       
            String msg = "Your Rental Request has been Aprroved";
            e.sendMail(msg,"Laptop" ,txtCustomerId.getText(), txtProductId.getText(), txtRentID.getText(), txtPrice.getText(),txtRentDate.getText(), txtReturnDate.getText(), txtEmail.getText());
            DisplayLaptopOnRent();
            DisplayLaptopRentalRequest();
            Reset();
             }

        }
        catch(Exception e)
        {
        e.printStackTrace();
    }
//        
    }//GEN-LAST:event_btnAprooveActionPerformed

    private void btnManagelaptopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagelaptopActionPerformed
        // TODO add your handling code here:
        LaptopManageJFrame lm = new LaptopManageJFrame();
        lm.setVisible(true);
        this.dispose();
//        LaptopRentJFrame lr = new  LaptopRentJFrame();
//        lr.setVisible(false);
    }//GEN-LAST:event_btnManagelaptopActionPerformed

    private void btnReturnLaptopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnLaptopActionPerformed
        // TODO add your handling code here:
        LaptopReturnJFrame lr = new LaptopReturnJFrame();
        lr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnReturnLaptopActionPerformed

    private void tblLaptopOnRentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLaptopOnRentMouseClicked


    }//GEN-LAST:event_tblLaptopOnRentMouseClicked

    private void btnDenyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDenyActionPerformed
        try {
            // TODO add your handling code here:
            String sql1 ="UPDATE Customer SET LaptopApprove = NULL  WHERE CustomerID = '"+txtCustomerId.getText()+"' ";
            c.updateDatabase(sql1);
            JOptionPane.showMessageDialog(this,"Request Denied");
            String msg = "Your Rental request has been Denied";
//            e.sendMail(msg,"Laptop" ,txtCustomerId.getText(), txtProductId.getText(), txtRentID.getText(), txtPrice.getText(),txtRentDate.getText(), txtReturnDate.getText(), txtEmail.getText());
            
        } catch (Exception ex) {
            Logger.getLogger(LaptopRentJFrame.class.getName()).log(Level.SEVERE, null, ex);
            
        }
            DisplayLaptopOnRent();
            DisplayLaptopRentalRequest();
            Reset();
    }//GEN-LAST:event_btnDenyActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        GadgetAdminLandingPage hl = new GadgetAdminLandingPage();
        hl.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LaptopRentJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LaptopRentJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LaptopRentJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LaptopRentJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LaptopRentJFrame().setVisible(true);
            }
        });
    }

    
    
//    private void DisplayLaptopList(){
//        String reg,brand,carmodel,status,price;
//        try{
//            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/rent","root","12345678");
//            st = con.createStatement();
//            rs = st.executeQuery("select * from laptop");
//            
//            DefaultTableModel model =(DefaultTableModel) tblLaptopList.getModel();
//            int rowCount = model.getRowCount();
//            for (int i = rowCount - 1; i >= 0; i--) 
//            {
//            model.removeRow(i);
//            }
//
//
//            while (rs.next()) {
//                 reg = rs.getString(1);
//                 brand = rs.getString(2);
//                 carmodel = rs.getString(3);
//                  status = rs.getString(4);
//                  price = rs.getString(5);
//                  String[] row = {reg,brand,carmodel,status,price};
//                  model.addRow(row);
//                               
//            }
//        
//        } catch (SQLException e)
//        {
//            e.printStackTrace();
//            
            
//        }
//        
//        
//        
//    }
    private void DisplayLaptopOnRent(){
        String reg,brand,carmodel,status,price;
        try{
            
            String sql = "select * from Laptop where (Status = 'Booked' and rentid IS NOT NULL )";
            ResultSet rs = c.selectDatabase(sql);
            DefaultTableModel model =(DefaultTableModel) tblLaptopOnRent.getModel();
            int rowCount = model.getRowCount();
            for (int i = rowCount - 1; i >= 0; i--) 
            {
            model.removeRow(i);
            }


            while (rs.next()) 
            {
                 reg = rs.getString(11);
                 brand = rs.getString(8);
                 carmodel = rs.getString(5);
                  String[] row = {reg,brand,carmodel};
                  model.addRow(row);
                               
             }
        
        } catch (SQLException e)
        {
            e.printStackTrace();
            
            
        }
        
        
        
    }
    
    
    private void DisplayLaptopRentalRequest(){
        String reg,brand,status,price,carmodel;
        try{
            String sql = "SELECT * FROM Customer where LaptopApprove = 'Requested' ";
            ResultSet rs = c.selectDatabase(sql);
            DefaultTableModel model =(DefaultTableModel) tblLaptopRentalRequest.getModel();
            int rowCount = model.getRowCount();
            for (int i = rowCount - 1; i >= 0; i--) 
            {
            model.removeRow(i);
            }


            while (rs.next()) {
                reg = rs.getString(1);
                brand = rs.getString(29);
                
                status = rs.getString(30);
                price = rs.getString(31);
                carmodel = rs.getString(27);
                String[] row = {reg,brand,status,price,carmodel};
                  model.addRow(row);
                               
            }
        
        } catch (SQLException e)
        {
            e.printStackTrace();
            
            
        }
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAproove;
    private javax.swing.JButton btnDeny;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnManagelaptop;
    private javax.swing.JButton btnReturnLaptop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblCustomerId;
    private javax.swing.JTable tblLaptopOnRent;
    private javax.swing.JTable tblLaptopRentalRequest;
    private javax.swing.JTextField txtCustomerId;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtProductId;
    private javax.swing.JTextField txtRentDate;
    private javax.swing.JTextField txtRentID;
    private javax.swing.JTextField txtReturnDate;
    // End of variables declaration//GEN-END:variables

    private void Reset() {
        txtCustomerId.setText("");
        txtEmail.setText("");
        txtPrice.setText("");
        txtProductId.setText("");
        txtRentDate.setText("");
        txtRentID.setText("");
        txtReturnDate.setText("");
    }
}


